### ISSUE TITLE
Release on steam ?

### ISSUE THREAD

**Issue by Slope123** [irzyxa/Volume2#154]
Just get Volume2 on Microsoft Store a couple hours ago, and as always Microsoft let me down again, it is still struggling to download it lol.

It would be nice to see Volume2 release on steam, people need to know this great software.

**Comment by irzyxa** [comment]
Done. It is going to be released on December 15th
[Download from Steam](https://store.steampowered.com/app/1832750)

**Comment by Slope123** [comment]
Wow
Looking forward to it :)

**Comment by irzyxa** [comment]
@ProDJ77 You can send me your payment details and I generate you the personal license, that you can use in any Volume2 version. You  can disable Autorun for WS version and install beta.

**Comment by ProDJ77** [comment]
Thanks for your response. This is my order details.

Greetings.

[image: Gmail] *Francisco Martinez ***@***.*** ***@***.***>>*
------------------------------
*Fwd: Your Microsoft order #3558262504*
------------------------------
*Francisco Martínez ***@***.***> 11 de enero de 2022, 02:05

Para: "Francisco Mtz." ***@***.***>
*No se muestran las imágenes externas.* -  Mostrar imágenes a continuación
<https://mail.google.com/mail/u/0/?ui=2&ik=0472cb2103&view=lg&permmsgid=msg-f:1721644715447993833&ser=1>

------------------------------
*From:* Francisco Martínez ***@***.***>
*Sent:* Monday, January 10, 2022 9:59:55 PM
*To:* ***@***.*** ***@***.***>
*Subject:* RV: Your Microsoft order #3558262504

Hi Alexandr,

I just bought the Microsoft Store version, could you please generate my
Volume² personal license? My email is: ***@***.*** or
***@***.***, I'm attaching the purchase details.

The license activate something? or its the same as the free license?

By the way, I had to uninstall the MS Store version due to I usually use
the latest Beta installer version.

Thanks in advance and greetings from Mexico City.


Francisco Martínez


------------------------------
*De:* Microsoft Store ***@***.***>
*Enviado:* lunes, 10 de enero de 2022 07:39 p. m.
*Para:* ***@***.*** ***@***.***>
*Asunto:* Your Microsoft order #3558262504

Important details regarding your Microsoft order
[image: Microsoft logo]
You are receiving this email because you completed a transaction with
Microsoft Store. This email is sent from a notification only address and
cannot accept incoming emails. Please visit our Support page
<https://support.microsoft.com/> if you have any questions.
Thank you for shopping with us on Tuesday, January 11, 2022.
Any downloads you bought, except preorders, are available now.

If you need help, we're here for you. In addition to free shipping and
returns, our Microsoft Store Promise
<https://www.microsoft.com/en-us/store/b/why-microsoft-store?OCID=ema_Purchase_StorePromise_US_062221>
includes
free virtual workshops, video tutorials, expert help, and more.

We also offer one-on-one help with Surface devices and accessories, gaming
devices, Microsoft 365, or Windows. If you’ve purchased a product for
personal use, book a free product expert appointment
<https://www.microsoft.com/en-us/store/b/online-computer-shopping-appointments?Wt.mc_id=Promo_Purchase_PersonalSetupTraining_US>
for
setup assistance or personal training. For business customers interested in
personal training, book a free appointment with one of our business product
experts.
<https://www.microsoft.com/en-us/store/b/business-consultation?Wt.mc_id=Promo_Purchase_SMB_PersonalTraining_US>
Order 3558262504
[image: Volume² - advanced Windows volume control]
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAADJHN6LEB6BBJC3JY5LNFUGAEZVANCFFE5ZFP3WJM3SJQC3MDLZOFTJ73JWWX25XBCA7DPS3VPVQE5ACM7G66RYTIAZDKOTNEQ7SXWMEJXHCLQ7HPD2RF6THDTZFREQUJBVT334JDUICALERAUPYZC7KSU4NEXSJX75NW4BPHSJ3J2Q2XEJP333L5DT4BGWS35KJ3TGQI2S7WCZPMP5TXQWXEV6RQTTTEQ7723ZRLHHPAK5H2U4ZZKU4STFUO4GAD4&d=AIAADADRD5MG3CVHST2MKEK2QLWTAPPBIIDOOZYM65G4TN4ODOBCVS2A3LER2MXDUT3UQPPXWH7NRF4CCGFXOYWMVSVNNSGGQ4W7RXWZOQNW3CXQ6UUOB33VOQUQVXQ2IRSA7GKRERD4ZWJ6HHUXU6LHCH6NF5CDYZSGHY5H73IESXJUXESOVHTG&i=AIAAC72J7XIDONHG3ZESPR375AKSGTJ5OBE5TXO5MKUVGNXWXFQBA5NCETAWWNRUJCTWVWXT4APHAV6YL4JMT2JKF5LAYHT2FOY7CTVVEU7YOGA7FSH7LNNUHMWJGQJ37ITUFFYMESXN35EQJPHA3LZE5M4NAK43ZLM674OFOWEFMYWDQNXWYQ3PJIQSLG6C77BK3IATFBT5HZHCAMIEF36TPYUCOMKERN55R5QKDDNEK26BG6TV26T72ZTKHYA5KU3FSF2UJD4ZCCUFRTFRCHAUF32OGBA>
Volume²
- advanced Windows volume control
( Alexandr Irza )
Quantity 1
MXN$121.55
Subtotal MXN$121.55
VAT MXN$19.45
Total MXN$141.00
Payment method
PayPal ***@***.***) MXN$141.00
View or manage your order
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAADTPX2EXE3RRSVISG264Q4FZ5IKZDBR7SLDKV3NLFEFHBULZRWZPNJUF76Z4HC5ZVIGJJ3H7XY43AMCMSHYUMNCZJ2LAQ5LL47SN45CS7A6WHQAPLIPPEMNX3YHLTXJQQZTNYM5TKFXOJZCX63YJC2NIWROCLSDI2KR45XQ5AIIMY5PM7NYOC3G3QVCTHNJ4RPFWA3CQYM4UUDTHE7V5FPKTJD2ZRSN34TUN45CQQRHI7Z23OPDIDQZAKXN7IXEOMMNKG3MI6AIAJPRWSOUKDESTTBHQ&d=AIAACF7RM35LTIUBQQBRTTH33SUXCVXWVANGO2RXKIG6HHRUFXFZUKNUMTQVMES6SF3RBNF3R7P7GCNQP3JSIBCW2GJLDPX7M2HVPMDE5INZU56P6LRXQUCYJWS2SD3Y7IMNKVD6J3I4TGKJCX6RST2OJ5O5BWYPKZPGUYUT2PIZNGG7DZYPF7OC&i=AIAACGHMVT5UCG6AGLAIHCS42DAV25OJV6WN5J3SZZRZFDJIOMVXG2ZX7LPW6TX6SSY67JV7VDLTJ6P2OKBPAUHAGS3YVGBPKS6MQFGPFJ3UL7HNGOSNOZNRML6H6X7L576QAHG2IOWDCXNKSNNZQVG64OGDMXYCSIPRSAGHBZSF53PRJ6YJVUTS2G4ISEIFNADULPHUDATIV2O6YJERVAXKG6HYVEAPIOWOC7Z3E6OWMSTOJJTPDT3J25K2OYFZC5NAUIZ6UQF2Y2FGZKFYHRIJCNT3NXI>
We recommend that you print and save this confirmation email and Terms of
Sale.
<https://www.microsoft.com/en-us/store/b/why-microsoft-store?OCID=ema_banner_why-msft-store_7102020>

Need to make a return? See our Return policy
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAACQFZ5BOP6BFZLZLDHLCEPIWGRHOTON6WJEKTTKR7SZF65KG4SWJ6R7ALEO2ARYDGW5QAHJZYDIVG62TNRF2PYCH2Z6FW2ELSVREBOIFVQIHTXOWZ25NFRJDFKIFQQCFL2YCDB4ERJQSDP4AY55PM6HKUXMY4GVCBHGNKCOKGJUSB2UCTVUP7&d=AIAACHGD4BPMUYUSF5ASFYT3ZVWP322QAB5OWQ3PJ2UT2FPUEGAE2FYTLMJDYOKEQFC73LTJG4ZL257CSK5SD5H3RE2IEFTQLWSKRBAU5NUEV3SGAM76VWTLOWN5XSYES7AH75SWLRSZFORZB7OA4ELP4LHQ5UCFBDH33AHSJV3VOVDHD5TDEWWP&i=AIAAC35J6L73RP5LHE7XAQ7HZS6YCKPYXNOVR6SQ5Q2KEJKZYHAUQ3IWNQFXV6YAYUJIKPTIH2GQXIBMOWEOKMRPRRHM7VEPVNYPLINFR5U6FGOZ56UCGAY76L46AYQ7NLLMG3ST5MQT3LPMLYE2Z7M5PM5D5AQTERIZOUZS2JJOKM6JWZAA2IWRNM65PUZ56N4CHKQK7RKE77HLWOENWNCCN5SAMFY7V343F46ESCZQCWQW3EV4RHTMXPQSEJ4QNRNJEU5EGWMDRV7JDO4QAC4TYJPAZSI>
to
learn more.

Microsoft respects your privacy. To learn more please read our Privacy
Statement
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAADIMGWQHL7TUFSK7WLUFJUZIM2J6BH3Z7U2JIESCHKSVRVAQEP2B6C6QARIWJS7C65TAV4JMHVO2LG5UILT6IHLXU2BJG526RWBH3IBZO6UPXSAPOFL7327VKX3UEF32WIW7IFUOUYEL75MVT3QDSFBMMY4HGHNZDJRPIBUTJQD6FYRFQUBZF&d=AIAACQIBKHLNM7ASOIJAZNEFBVWGFZIXWBMOVIH5H5GIIJGWZW4XS2SW6EZSLFREFATOWMNFOSGQE52ERPIIHA6KIO7ZLVDLI36FNIXQSM2Y5FACCNM4DN57GOU7IA4CV3VSN5WMRXBKS35QUGLCJPHKYSO66I5N57UVR3C4AEPZPFSRKYZMQRMO&i=AIAADYEM2IHA7DXL3RS5YHWA6YZKYPOHJY2UPGNAYGCKPWOIFQTQYANECF4UZPA5RR3JXJRJ64XTUFS24LQACOSVXRXA3ASK7OHCVNTP77JATJYVBTQ3K47KQTX5SZK7HL6ELS7JZDW6VYVKX535XLHUJXR23C7BLBF7VQBPZFK4Q2OWRKA2MODRUARD7PPKA6N223NRD4QMTOBGNXUBP7Q75GTW7652WL4XA3MNYC3RHR6NTHM4ZGJXSN562ZXGBRY2YP5SJ2DRHVM2BYO2V3MIS7VGLNQ>
.

Account questions? Visit Customer Support
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAAD57DFDONIEERRWDCKLSXVBCMLWVX2VBRMJ3KBE7XBXPPVX5AAQV4KAZDLQPHX5L34725I6Y6YGYDQ5SWUWU76PIVRB366IO5RALPYXAZVQAJE43NZ5OACH6INH2BRDRSNKOWIHSSTGSJKY7PLTU3WRFZDDQ&d=AIAADVUHCWJ3ZDAXRA7ZT242KOE4ZTE3F2QTG5COARAKSLH5BDVN4NDEUNZ4PBNJTQJLNTTH74ZEDLED7ZQRG3DTFV63K42Y7VTMSPVLHELUNPHSVSMSQNK6NHVMXJOLLQEKP6ZBW4MYJVERB53IC4FUUPI2OP5JJCTNB4AQ43IP5JF5IEVT3ITW&i=AIAACHVAR26LQEWIHVTVU64KTPEQXX6STZJBLX2MHCFM6QZDSMOA5AHCXCLS3MUDTIVDUFLEXKTMDDQBM66QQDUUGQIVLF65YWRUOCMNOCMVSKC55BJVOF3DHG6EAV6VWEQQHYQVR7DRQOWLUJ5TTAFANSVQL7ZTKFRZS3WZRINJYZEJ36GJUA6PLW63S7VK2XNXKR2WWMGYLN2GD6BPFPNT2GLF7J6UGKKRQGQB2G4RGW2KGHS3RNG4LTRCAMII57O2E5OFMBXHDLBRDJTQUU4WH2WRZTA>
.

View the Store Terms of Sale
<https://mucp.api.account.microsoft.com/m/v2/c?r=AIAAC573OGQ4QAP6TEGE6OSKIETR4Z7MPV2Z2BJMR5K2LT2YUSA22HHJ6N2J4XKWCFPBV3JDVEYKYAM7ERWYZAICJHLU7FUFV63B5KNCY3WUFNED2M5YT46U5VV27O2B7IPLFWR35ZVEKBV3FETVQU5PSXRNIU6XM7J75KIMUUG4U7UISTODANQJ&d=AIAAC6TJ2FJDB7NADNOI6CTD64UZGDTIWFLKYMRZDQXY2KSFY7ZWUOD7BOSZN6R44UZYJYE7B2Y6UN5MCS4LHHZRDO7OIDDLEPNRAVM5TXF5FDESQBJOC7AU4JH3NPFDO4V3VUBMOE7CNW3MKKHMHRNI2BJV6NLSO4IBGXQXHXDKPGX4HCU65MJQ&i=AIAADFYTHCRUK4QA6NN6IHR2CKPBR42GHB27OEZ3LBGQJHSXNS3XYVNLU6PTZ7E5V465N5VQL7GC6GVAPFBJSIRE5FVRFN7THL7KIPFNKBUMNZMR77FO6QU3XGMW62ZZL4KLRU5PWMCFIMRNTHSIG5Y7YAWJ6Y5LBNE3TCZAGHN7HINBTFR2S76NILFM3L7JFKSHA2SDGQAHMYD3QUTSRMU7AI2HXLSNL3HQHT3ADSR3CTHVP7JKRELCETPDPLANYDQ2ABRNVMGCNCGS2XWFITR7SNF2KTI>
.

Dates are displayed per Coordinated Universal Time. Order date may vary
based on your location.

Microsoft Corporation, One Microsoft Way, Redmond, WA 98052 USA
<https://www.google.com/maps/search/Microsoft+Way,+Redmond,+WA+98052+USA?entry=gmail&source=g>

**Comment by irzyxa** [comment]
@ProDJ77 on my email irzyxa@gmail.com, because I need your email to send license

**Comment by ProDJ77** [comment]
Ok. Sending right now. Thanks.
