### ISSUE TITLE
Add "% to icon title

### ISSUE THREAD

**Issue by rafi-d** [irzyxa/Volume2#171]
Can you add % to the volume icon title please ? like 50**%** , which is much more readable.

**Comment by irzyxa** [comment]
What do you mean? Where should % be added? To hint/tooltip? Any screenshots?

**Comment by rafi-d** [comment]
Here:
![image](https://user-images.githubusercontent.com/2458280/148893665-5df07f16-7542-4099-848e-d24df6202497.png)

**Comment by irzyxa** [comment]
It is very small icon just 16x16 pixels so I don't think percent fits there. You can try to do this by yourself. Go to Volume2 folder, Skins/Volume2 Default and try to edit any png file in any graphic designer.

**Comment by rafi-d** [comment]
It might not be the correct approach (being so small)... You should try and implement it as a static text char readout (in XML?) over the graphics. No idea how to do that...

**Comment by irzyxa** [comment]
So here is realistic size of tray icon and I cannot add any extra characters there:
![image](https://user-images.githubusercontent.com/5119360/148901595-c1029cda-0659-4f45-b292-e77ce831b24d.png)
FYI: All skins have been drawn in graphic programs not drawn in real time, because icon should look differently for different taskbar size (High DPI). Icons can be: 16px, 20px, 24px,32px and for different sizes you have different amount of space so you can draw more detailed icon.

**Comment by rafi-d** [comment]
It is  pretty good when the size is small. I'd shift everything one pixel to the left, to complete the "%" symbol bottom right, and try to program it not to overlap the red color of the digit...

**Comment by irzyxa** [comment]
But we have 100% that is much bigger and does not fit.

**Comment by rafi-d** [comment]
You are right... I forgot...
