### ISSUE TITLE
Brightness control doesn't work anymore after the Windows 1903 update

### ISSUE THREAD

**Issue by fttx** [irzyxa/Volume2#62]

**Comment by s3n0** [comment]
Hello.

Hm... no problem here on my Windows10 - build 1903.

Write more details for the developer: 
- the exact type of graphics card (brand, model, type)
- the exact driver version of graphics card
- the exact type of monitor (brand, model, if you also know the firmware version)
Try changing the brightness level directly in the Windows10 system.

**Comment by fttx** [comment]
I'm using it on my laptop Dell XPS 9550, that has an i7 6700HQ  (HD Graphics 530) and a NVIDIA GeForce GTX 960M. NVIDIA Driver version: 23.21.13.9125

I'm talking about the software brightness control (overlay), the native brightness level works.

**Comment by s3n0** [comment]
Changing brightness in Windows 10 works ? If not, then it's a Windows problem, not a Volume2 utility problem. For example, like this: https://www.youtube.com/watch?v=mDH43DPo8Yc

**Comment by fttx** [comment]
Fixed, you were right, it was a driver issue. So the Volume2 brightness control isn't a software overlay? It allows me to lower the brightness much more compared to the windows brightness control

**Comment by s3n0** [comment]
I don't know, sorry. I'm not the author of Volume2.

Operating systems have become very complicated over the last 20 years (in terms of programmer development). Linux is a bit better than Windows. There is easier access to hardware.

Where are the lost times when it was enough to call one short procedure in MS-DOS with the help of INT 10h interruption to change the brightness level on the VGA card using the current color palette. Alternatively, use IN / OUT instructions for direct control of brightness levels. Everything was complicated because everything today must be universal :-D. Unfortunately, the result of the whole effort is that everything is incredibly complicated and incompatible.
