### ISSUE TITLE
No way to edit system tray skins

### ISSUE THREAD

**Issue by ThEditor** [irzyxa/Volume2#91]
I would like a feature where I can change the volume at which the image of the system tray changes.
Like in windows at 0 level is the first image, then at 1 volume second image, then at 33 third and at 66 fourth, but in Volume2 first image is at 33, second at some other value.
I would like to change these values so I could replicate the original windows tray.

I would also like to have a feature in which I could add my own skins for the system tray icon.

**Comment by irzyxa** [comment]
You can use any resource editor to change *.lsk(it is just renamed dll) or any image editor if it is folder skin.
My opinion that Windows tray icon works incorrectly, because it nowhere shows 0 icon, it just shows mute icon. But you can replicate original behavior. You should change Standard 10 skin by removing first icon and enable 2 options in Volume2
![image](https://user-images.githubusercontent.com/5119360/80859277-0c5b0300-8c68-11ea-9e3c-b8d88383298f.png)

**Comment by irzyxa** [comment]
Also you can use this [documentation](https://github.com/irzyxa/Volume2/blob/master/Docs/Volume2%20Creation%20Skins%20(RU).pdf) + Google translate to create skins yourself.

**Comment by irzyxa** [comment]
I should change calculation icon index for your request. It will be available in the next version.

**Comment by ThEditor** [comment]
Thanks for the quick help :D

**Comment by irzyxa** [comment]
Fixed. Version 1.1.6.421
